update preload and add the as attribute
w3c/html pull request #1053
Opened 2017-10-23 17:00 UTC by siusin

- define the `preload` keyword;
- add the `as` attribute to the `link` element;

To fix #1044 , [tests](https://wpt.fyi/preload/reflected-as-value.html) are already in place.

2017-10-23 18:23 UTC, plehegar approved these changes

2017-10-24 15:16 UTC, chaals requested changes
Please add the changes to the changes section.

2017-10-24 15:33 UTC, siusin commented
Thanks for reminding, @chaals .

Changes section updated.

2017-10-24 20:27 UTC, chaals approved these changes

2017-10-24 20:28 UTC, merged