Update HTML spec to match ARIA in HTML spec
w3c/html pull request #1133
Opened 2018-01-03 19:46 UTC by scottaohara

Based on [issue 894](https://github.com/w3c/html/issues/894), I've reviewed each of the HTML elements and their allowed ARIA `role`s & `aria-*` attributes and have made multiple updates to align the HTML spec with the information provided in the latest editor's draft of [ARIA in HTML](https://w3c.github.io/html-aria/#allowed-aria-roles-states-and-properties).

2018-01-03 22:42 UTC, chaals requested changes
These changes all look good to me - thank you for this effort.

Would you please add an entry to the changes.include list noting that there was a significant update and pointing to this PR, to help external reviewers?

2018-01-04 12:16 UTC, scottaohara commented
Hi @chaals 

I updated the change.include per your request.

Also, I spoke with @stevefaulkner this morning and I'm going to be adding in the missing `dpub roles` that are in the ARIA in HTML spec, but are not currently present in the HTML spec.  

I'll get those as part of this PR asap.

2018-01-08 12:56 UTC, chaals approved these changes

2018-01-09 02:18 UTC, scottaohara commented
@stevefaulkner & @chaals  I have added the DPub roles from ARIA in HTML spec to this PR.

Unless there is anything else to add or any fixes/updates I need to make, I think this is set?

Thanks

2018-01-14 13:05 UTC, merged