First draft for issue 278
w3c/html pull request #1142
Opened 2018-01-16 09:28 UTC by patricia-gallardo

This is my first draft for issue 278

2018-01-16 09:55 UTC, LJWatson commented
This LGTM. Ping @Chaals for final review.

2018-01-17 05:28 UTC, cynthia commented
Just as a passing remark - I think the commit message could have been worded/formatted better.

2018-01-17 06:38 UTC, cynthia commented
@chaals suggested I elaborate on how - so here is the list of options.

1) Squash into a single commit and rewrite commit message. (this can be done with the "Squash and merge" button on GH's web UI.)
2) Rebase. (This would be what would happen normally if there was critic available. Unfortunately that isn't the case, but it can be done from the CLI..)

Normally amend would be an option, but with the fixup commit that is a bit harder.

2018-01-17 07:32 UTC, chaals commented
Sangwhan suggested:

> Squash into a single commit and rewrite commit message. (this can be done with the "Squash and merge" button on GH's web UI.)

Since I use the Web UI to Squash and merge, I rewrite the messages as relevant. (To the best of my ability...)

We should probably document this in our documentation, but I don't think you should worry about it overmuch for this case.

2018-01-21 17:05 UTC, chaals requested changes
The technical bit looks good...

Please
* update the changes section to note this
* add relevant acknowledgements
* update the attributes index

2018-01-23 08:28 UTC, siusin commented
The test looks great! \o/

@patricia-gallardo could you update sections/events.include and add the focusin and focusout events as well?

2018-01-30 23:24 UTC, chaals commented
Bruce will work on this on Friday (deadline day for the milestone)

2018-02-02 11:33 UTC, chaals approved these changes

2018-02-02 11:46 UTC, merged

2018-02-02 11:56 UTC, patricia-gallardo commented
Thank you @brucelawson and @chaals for picking this up and finishing it. I still have quite a bit to learn.