update the usage of cryptographic nonce metadata
w3c/html pull request #1177
Opened 2018-02-02 04:41 UTC by siusin

To fix #198 :
1. update a few sections about the cryptographic nonce metadata;
2. add the integrity attribute;

2018-02-02 10:37 UTC, chaals requested changes
Some editorial and linking changes, but the content looks OK to me.

2018-02-02 10:37 UTC, chaals commented on single-page.bs
> +#  ************************** INFRA *************************************
this is unnecessary, bikeshed already has this reference. (Plus it is unnecessary as noted above)

2018-02-02 10:37 UTC, chaals commented on sections/webappapis.include
> +          <p>Let <var>fetch options</var> be a <a>script fetch options</a> whose <a>cryptographic nonce</a> is <var>initiating script</var>'s <a>fetch options</a>'s
be a script settings options -> be a set of...

2018-02-02 10:37 UTC, chaals commented on sections/webappapis.include
> +  : A <dfn>id</dfn>
A id -> An id

2018-02-02 10:37 UTC, chaals commented on sections/webappapis.include
> +  : A <dfn>execution ready flag</dfn>
A execution -> An execution

2018-02-02 10:37 UTC, chaals commented on sections/webappapis.include
> +  :: A <a>script fetch options</a>, containing various options related to fetching this
A script fetch options -> A set of...
or 
-> A script fetch options object

2018-02-02 10:37 UTC, chaals commented on sections/semantics-scriptings.include
> +  18. Let options be a <a>script fetch options</a> whose <a>cryptographic nonce metadata</a> is
a script fetch options -> a set of script...
or -> a script fetch options object

2018-02-02 10:37 UTC, chaals commented on sections/semantics-document-metadata.include
> +  1. If the <{link/href}> attribute's value is the empty string, then return.
note comment below on consistent terminology in algorithms.

2018-02-02 11:17 UTC, siusin commented
PR updated. Thanks for the review @chaals .

2018-02-02 13:19 UTC, chaals requested changes
Thanks for the update.

Unfortunately there are a handful more editorial and nitpicky things - it seems I forgot to add many of my comments to the review before, and found some I had missed

Also, at https://w3c.github.io/html/dom.html#global-attributes the nonce attribute doesn't link to a definition, but it should...

2018-02-02 13:19 UTC, chaals commented on sections/changes.include
> +            <dd>Fixed <a href="https://github.com/w3c/html/issues/198">issue 198</a></dd>
you also added SRI, right?

2018-02-02 13:19 UTC, chaals commented on sections/semantics-document-metadata.include
> +  1. If the <{link/href}> attribute's value is the empty string, then return.
No need to do anything here.

2018-02-02 13:19 UTC, chaals commented on sections/semantics-scriptings.include
> +      attribute with <a>strip leading and trailing ASCII whitespace</a>.
This line should read:

> ` attribute after <a>stripping leading and trailing white space</a>. `

to pick up the term defined in the spec.

2018-02-02 13:19 UTC, chaals commented on sections/webappapis.include
> +   <dt><dfnfor="script">referrer policy</dfn></dt>
dfn for (missing space)

2018-02-02 13:19 UTC, chaals commented on sections/webappapis.include
> +  empty string, <a>parser metadata</span> is "<code>not-parser-inserted</code>", <a>credentials mode</a> is "<code>omit</code>", and <a>referrer
please split the line differently so you don't have a line break inside the link `<a>referrer policy</a>`

2018-02-02 13:19 UTC, chaals commented on sections/webappapis.include
> +  <p>For any given <a>script fetch options</a> <var>options</var>, the <dfn>descendant script
please change line breaks so the `dfn` isn't split over two lines

2018-02-02 13:19 UTC, chaals commented on sections/webappapis.include
> +  fetch</dfn> hook, which takes a <a>request</a> and an <dfn for="fetching scripts"><var>is top-level</var></dfn> flag. The algorithm must complete with a <a>response</a> (which may be a <a>network e
line breaks...

2018-02-02 13:19 UTC, chaals commented on sections/webappapis.include
> +  To <dfn>fetch a classic worker script</dfn> given a <var>url</var>, a <var>fetch
line breaks...

2018-02-02 13:19 UTC, chaals commented on sections/webappapis.include
> +       <a>mode</a> is "<code>same-origin</code>", <a>credentials mode</a> is "<code>same-origin</code>", <a>parser
line breaks

2018-02-02 13:19 UTC, chaals commented on sections/webappapis.include
>    4. Return from this algorithm, and run the remaining steps as part of the fetch's <a>process
while you are here, can you lease fix this line break too?

2018-02-02 13:19 UTC, chaals commented on sections/webappapis.include
> +  given a <var>url</var>, a <var>fetch client
line breaks for 2 lines in a row

2018-02-02 13:19 UTC, chaals commented on sections/webappapis.include
> +      <a>referrer</a> is <var>referrer</var>, and <a>client</a> is <var>fetch client settings
line breaks

2018-02-02 13:19 UTC, chaals commented on sections/webappapis.include
> +   <p>By default, not supplying the <a>perform the
line breaks

2018-02-02 13:19 UTC, chaals commented on sections/webappapis.include
> +   metadata</a> to <var>options</var>'s <a>cryptographic nonce</a>, its <a>integrity metadata</a> to <var>options</var>'s
remove the final "s" at the end of the line - should read

> `...<var>options</var>' `

2018-02-02 13:19 UTC, chaals commented on sections/webappapis.include
> +  <p>Given a <a>request</a> <var>request</var> and a <a>script
line breaks

2018-02-02 13:19 UTC, chaals commented on sections/webappapis.include
> +      distinct from the <a>environment settings object</a>'s <a>responsible
please don't split the link over 2 different lines

2018-02-02 13:19 UTC, chaals commented on sections/webappapis.include
> +  :: Either a <a>Script Record</a>, for <a>classic
please don't split the link over 2 different lines

2018-02-02 13:19 UTC, chaals commented on sections/semantics-document-metadata.include
> +  The <dfn element-attr for="link"><code>integrity</code></dfn> attribute represents the <a>integrity metadata</a> for requests which this element is responsible for. The value is text. The attribute
please split this line for easier reading in tools that don't auto-wrap. E.g. < 100 characters / line ...

2018-02-04 21:57 UTC, chaals approved these changes

2018-02-04 22:42 UTC, merged