UTF-8 All The Things
w3c/html pull request #1273
Opened 2018-03-01 22:15 UTC by edent

* Update spec to insist on UTF-8
* Fixes #1039

2018-03-08 17:08 UTC, chaals requested changes
If we are going to make a change requiring UTF-8 from authors, we should ask for very wide review.

Meanwhile, requested a couple of small changes at least to be considered...

2018-03-08 17:08 UTC, chaals commented on sections/semantics-document-metadata.include
> +  Authoring tools should default to using <a>UTF-8</a> for newly-created documents. [[!ENCODING]]
If we require utf-8 then this (and similar requirements) have to be a must.

2018-03-08 17:08 UTC, chaals commented on sections/semantics-document-metadata.include
> +  The only acceptable character encoding declaration for the modern web is <a>UTF-8</a>.
Is it possible to rephrase this less didactically?

2018-03-08 17:08 UTC, chaals commented on sections/semantics-document-metadata.include
> +  encoding used must be an <a>ASCII-compatible encoding</a>.
why doesn't this just require utf-8?

2018-03-08 17:08 UTC, chaals commented on sections/iana.include
> +          "<code>utf-8</code>". [[!ENCODING]]
If we just enforce a string, there is no normative dependency on the encoding spec here.

2018-03-14 11:36 UTC, edent commented on sections/semantics-document-metadata.include
> +  The only acceptable character encoding declaration for the modern web is <a>UTF-8</a>.
No :-)

That is, I'm not sure how else to phrase it in order to get the point across. Suggestions welcome.

2018-03-14 11:38 UTC, edent commented
Regarding wide review.  UTF-8 is now 91% of the web https://w3techs.com/technologies/overview/character_encoding/all

Happy to hear arguments why it shouldn't be mandated.

2018-03-27 13:31 UTC, edent commented on sections/semantics-document-metadata.include
> +  The only acceptable character encoding declaration for the modern web is <a>UTF-8</a>.
> The problems outlined here go away when exclusively using UTF-8, which is one of the many reasons that is now the mandatory encoding for all things.
> https://www.w3.org/TR/2018/CR-encoding-20180327/

2018-03-29 06:42 UTC, chaals requested changes
This needs to be noted in the changes section.

2018-03-29 06:42 UTC, chaals commented on sections/iana.include
> +          This parameter serves no purpose; it is only allowed for compatibility with legacy servers.
"This parameter is for compatibility with legacy servers", no?

2018-03-29 06:42 UTC, chaals commented on sections/semantics-document-metadata.include
> +  The only acceptable character encoding declaration for the modern web is <a>UTF-8</a>.
yeah, this is hardly a high-order problem.

2018-03-29 08:59 UTC, edent commented
@chaals I have updated the Changes file.

2018-03-29 09:52 UTC, chaals approved these changes

2018-03-29 12:09 UTC, merged

2018-05-31 17:09 UTC, r12a commented
See comments from the i18n WG on this change at https://github.com/w3c/html/issues/1039