Unescape HTML - as per style guide
w3c/html pull request #1280
Opened 2018-03-04 11:15 UTC by edent

This patch turns `&quot;` into `"` and `&dagger;` into `†` etc.

Makes the source easier to read and search.  Complies with #1193

2018-03-06 14:48 UTC, edent commented
This has passed CI - I don't know why it is saying it hasn't https://travis-ci.org/w3c/html/builds/348892330?utm_source=github_status&utm_medium=notification

2018-03-08 17:15 UTC, chaals requested changes
Can we turn a list into a list? Other than that, LGTM - feel free to make the change or explain why not, then merge it yourself

2018-03-08 17:15 UTC, chaals commented on sections/editing.include
> +    input would be channeled from the graphical system to ① the Web browser, then to ②
Why not make these a normal ordered list?

2018-03-09 10:13 UTC, edent commented on sections/editing.include
> +    input would be channeled from the graphical system to ① the Web browser, then to ②
Because in translation, I assume the ol-li could become 一,二,三,四. Whereas the image has circled numbers on it.

2018-03-09 10:14 UTC, merged

2018-03-09 10:39 UTC, chaals commented on sections/editing.include
> +    input would be channeled from the graphical system to ① the Web browser, then to ②
Fair enough, thanks.