Adds capture attribute
w3c/html pull request #1366
Opened 2018-04-12 17:31 UTC by LJWatson

* First draft (needs careful review)
* Adds capture to list of allowed attributes
* Adds capture to the table of allowed attributes per type state
* Adds capture to the bookkeeping information for each type state
* Adds section to locally reference capture (pointing to HTML Media Capture as the normative deifnition
* Will fix #1296 .

2018-04-12 19:43 UTC, LJWatson commented
[Tests for the ```input/capture``` attribute](https://w3c.github.io/test-results/html-media-capture/all.html)

2018-04-14 10:28 UTC, chaals requested changes
The Device and Sensors WG should be listed in acknowledgements.

This should be listed in changes.

I have not yet reviewed carefully for technical accuracy - it looks OK, but diff format is almost unreadable for this. So that check will take a little more time ;(

2018-04-14 10:28 UTC, chaals commented on sections/semantics-forms.include
> +  The <dfn element-attr for="input"><code>capture</code><dfn> attribute is defined in the [[!html-media-capture]] specification. The <code>capture</a> attribute specifies the preferred facing mode fo
mismatched element (opens as `code`, closed as `a`.

2018-04-14 10:28 UTC, chaals commented on sections/semantics-forms.include
> +       <{input/dirname}>,
Odd whitespace insertion - probably not critical (although sometimes whitespace oddities break the bikeshed builder).

2018-04-14 10:28 UTC, chaals commented on sections/semantics-forms.include
> +    <dd><{input/capture}> - Specifies the preferred facing mode for the media capture mechanism, defined in [[!html-media-capture]]</dd>
There should be a direct link for the attribute. As mentioned offline, I will make a PR against your branch to do that.

2018-04-14 10:28 UTC, chaals commented on sections/semantics-forms.include
> +  The <dfn element-attr for="input"><code>capture</code><dfn> attribute is defined in the [[!html-media-capture]] specification. The <code>capture</a> attribute specifies the preferred facing mode fo
Rather than defining the attribute in here we should probably refer to the source spec. I will make a PR against the branch to do that.

2018-04-14 14:29 UTC, LJWatson commented
@Chaals done.

2018-04-17 13:15 UTC, chaals approved these changes

2018-04-17 13:15 UTC, merged