only select browsing context by name within unit of related...
w3c/html pull request #1406
Opened 2018-04-24 15:07 UTC by chaals

First cut at matching Firefox/Chrome implementation
fix #262

2018-04-24 15:09 UTC, chaals commented
cc @0x1a0ran

2018-04-25 13:32 UTC, siusin requested changes
These changes make sense to me, except for two minor editorial bugs.

Thanks!

2018-04-25 13:32 UTC, siusin commented on sections/acknowledgements.include
> +  Xioran Wang,
s/Xioran/Xiaoran

2018-04-25 13:32 UTC, siusin commented on sections/changes.include
> +  <dt><a href="https://github.com/w3c/html/pull/1406">Only elect a browsing context by name</a>
s/elect/select

2018-04-25 14:24 UTC, siusin approved these changes

2018-04-25 14:24 UTC, merged