update to prose
w3c/html pull request #1444
Opened 2018-05-17 13:12 UTC by scottaohara

fixes #1443

Adds note about elements described as transparent.

Other minor wording updates to the previous prose of this section.

2018-05-23 11:12 UTC, patricia-gallardo commented
In the new note I think it would be more easily understandable if it provided an example of how this could be used.

2018-05-23 11:14 UTC, patricia-gallardo requested changes
Please add an example on the new note

2018-05-23 11:17 UTC, chaals requested changes
question, request for less jargon-y prose

2018-05-23 11:17 UTC, chaals commented on sections/introduction.include
> +        An exception to disallowing <a>block box</a> within <a>inline box</a> rendered elements
Can you call these something clearer? "elements that are typically rendered as a ..."? 

(sorry, no better ideas right now)

2018-05-23 11:17 UTC, chaals commented on sections/introduction.include
> +        An exception to disallowing <a>block box</a> within <a>inline box</a> rendered elements
Is this the only exception, or are there others (which is what seems to be implied here)?

2018-05-23 12:52 UTC, scottaohara commented
@patricia-gallardo & @chaals,
Added some quick examples and reworded/rearranged the prose a bit.  I worry about adding too much more to this section of the introduction, so I make mention that people should refer to the elements called out here, and other transparent elements, for additional info.

2018-06-04 21:54 UTC, scottaohara commented
@chaals any more that needed to be done on this?

2018-06-05 00:27 UTC, chaals approved these changes

2018-06-05 00:28 UTC, chaals commented
Looks good to me. @patricia-gallardo, if you are happy please merge this.

2018-06-19 14:08 UTC, cynthia approved these changes

2018-06-19 14:10 UTC, merged