fix wrong position of the Macintosh Uniform Type Identifier for html
w3c/html pull request #1454
Opened 2018-05-24 17:35 UTC by siusin

@polx

2018-05-24 20:55 UTC, polx reviewed
Looks good for the changes in iana.include.
I do not see if the changes.include modification to be connected, maybe adjust the comment?
paul

2018-05-24 21:30 UTC, chaals approved these changes
Looks OK to me...

2018-05-24 21:32 UTC, chaals commented
@polx Not sure if this needs to be listed in the changlog. I was leaning against it, but on reflection I suspect it should...

2018-05-24 21:32 UTC, chaals requested changes
Please note the change in the changelog, per @polx' comment

2018-05-29 16:18 UTC, siusin commented
Done. Thanks @polx and @chaals .

2018-06-04 12:27 UTC, chaals approved these changes

2018-06-04 12:30 UTC, merged