Final changes for a "clean" Section 3.
w3c/html pull request #752
Opened 2016-12-14 21:28 UTC by travisleithead

Fix #738
Fix #739
Much linking improvement in Section 3 (and beyond).

2016-12-15 18:45 UTC, arronei commented on sections/infrastructure.include
> +  Unicode strings, as defined in the WHATWG Encoding specification. An <a>encoding</a> has an
WHATWG doesn't have specifications it has standards. I think you will want to change this text

2016-12-15 18:46 UTC, arronei commented on sections/infrastructure.include
> +    Since support for encodings that are not defined in the WHATWG Encoding specification is prohibited,
Multiple cases of the "standard" issue

2016-12-15 18:48 UTC, arronei requested changes

2016-12-15 18:48 UTC, arronei commented on sections/semantics-forms.include
> +  In HTML markup and form submission dates and times are always written in a locale-neutral format derived from the ISO-8601 specification. For example, dates are generally in a format such as 2016-0
Line wrapping

2017-01-04 00:11 UTC, travisleithead commented on sections/infrastructure.include
> +  Unicode strings, as defined in the WHATWG Encoding specification. An <a>encoding</a> has an
Fixed in more recent commit

2017-01-04 00:11 UTC, travisleithead commented on sections/infrastructure.include
> +    Since support for encodings that are not defined in the WHATWG Encoding specification is prohibited,
Ditto above.

2017-01-04 00:15 UTC, travisleithead commented
Comments all addressed. Local-building before committing...

2017-01-04 00:16 UTC, merged