Issue #524 'creator context security'
w3c/html pull request #772
Opened 2017-01-16 02:35 UTC by adanilo

Port whatwg/html@a5853c3
Note, workers change in #1561 out of scope in HTML 5.2 - needs to
go into workers spec.

This is for issue #524

Note, obsoletes PR#615 which was referring to a removed repository on my side.

2017-01-18 01:48 UTC, travisleithead requested changes

2017-01-18 01:48 UTC, travisleithead commented on sections/browsers.include
> +  <p>If a <span>browsing context</span> <var>context</var> has a <span>creator browsing
If you want `browsing context` to link, it must be in an <a> tag, not a span... :( You can also now use a more compact syntax for links: `[=browsing context=]` to save 3 bytes :)

2017-01-18 01:48 UTC, travisleithead commented on sections/browsers.include
> +  context</span> <var>creator</var>, it also has the following properties. In what follows, let
Also, please avoid line-wrapping content inside a link--makes it a bear to search-replace later...

2017-01-18 01:48 UTC, travisleithead commented on sections/browsers.include
> +   <dd><var>creator document</var>'s <span>origin</span></dd>
Try out the compact `<var>` syntax and save 9 bytes! `|creator document|'s`

2017-01-18 01:48 UTC, travisleithead commented on sections/browsers.include
> +  <dl>
Also available/preferred: `<dl>` and it's respective `<dt>` and `<dd>` markup can be compactly re-written as:

```
  : define term
  :: define definition
``` 
and Bikeshed will expand it for you.

2017-01-18 01:48 UTC, travisleithead commented on sections/browsers.include
> +  <div w-nodev>
Is this `<div>` needed?

2017-01-18 04:45 UTC, adanilo commented on sections/browsers.include
> +  <div w-nodev>
Probably not, but it was in the WHATWG version and for consistency I pulled it in

2017-01-18 23:38 UTC, travisleithead requested changes

2017-01-18 23:38 UTC, travisleithead commented on sections/browsers.include
> +   <dd>|creator document|'s <a data-x="concept-document-url" for="/">URL</a></dd>
data-x is not used by Bikeshed; please remove it.
for="/" will lead to the wrong link, rather you want to link to "concept-document-url" (see line ~425 of single-page.bs), which can be done by using the reference "document url" and displaying "URL" (line ~64 of browsers.include). So, long story short, use `[=document url|URL=]` for this.

2017-01-18 23:38 UTC, travisleithead commented on sections/browsers.include
> +   <dd>|creator document|'s <a for="/">origin</a></dd>
This should link to `[=concept/origin=]`

2017-01-18 23:38 UTC, travisleithead commented on sections/browsers.include
> +   <dd>|creator document|'s <a data-x="document base URL">base URL</a></dd>
You can drop the `data-x` attribute and value; as noted above, not used.

2017-01-18 23:38 UTC, travisleithead commented on sections/browsers.include
> +   <dd>|creator document|'s <a data-x="concept-document-referrer-policy">referrer policy</a></dd>
... and same here

2017-01-18 23:38 UTC, travisleithead commented on sections/browsers.include
> +   |creator document|'s <span>relevant settings object</span></dd>
That `<span>` should be an `<a>`. In general, whenever you see a `<span>` question it. `<span>` is used by Anolis for linking (which is what the WHATWG source code uses). For Bikeshed, it must be an `<a>` (or any of the other flavors of autolinking it supports).

2017-01-20 15:34 UTC, travisleithead approved these changes
Super! Thanks!

2017-01-20 15:34 UTC, merged