Adds changelog for WD6
w3c/html pull request #862
Opened 2017-04-03 15:39 UTC by LJWatson

Changes between WD5 and WD6.

2017-04-04 04:53 UTC, chaals requested changes

2017-04-04 04:53 UTC, chaals commented on sections/changes.include
> +
There should be a fixed version link for the *following* reference to WD5

2017-04-04 04:53 UTC, chaals commented on sections/changes.include
> +  <dl>
Missing changes to menu/menuitem:

[Make menu and menuitem match reality](https://github.com/w3c/html/commit/0b959a586e54fe4145b69303ebb11755cea26c09)
Substantive changes:
*remove `HTMLElement.contextmenu` IDL attribute
*remove the `radio` and `checkbox` types for menus
*Make `menuitem` have content, as per implementation.
*A `menuitem` makes a command if it is labeled
*change terminology from "popup menu" state to "context menu" state.

2017-04-04 04:53 UTC, chaals commented on sections/changes.include
> +  </dl>
Missing [allow role="none" on `img`](https://github.com/w3c/html/commit/0b959a586e54fe4145b69303ebb11755cea26c09)

For `img alt=""` only

2017-04-04 17:20 UTC, travisleithead approved these changes

2017-04-17 18:23 UTC, chaals commented
So there is a changelog in the Working Draft... meaning this PR can just be closed, no? @LJWatson

2017-04-17 19:10 UTC, closed without merging